name: GitHub terraform

on:
  workflow_dispatch: 
#   repository_dispatch:
#    types: [my-event]
  
env: 
  aws-region: us-east-1

jobs:
  terraform:
    name: terraform 
    runs-on: ubuntu-latest
    
    
    
    defaults:
      run:
        working-directory: ./module

    steps:
      - name: checkout
        uses: actions/checkout@v3
#         with:
#           ref: ${{ github.event.client_payload.ref }}
#       - run: echo ${{ github.event.client_payload.sha }}
         
      - name: Terraform HasiCorp SetUp
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: AWS Credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws-region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: terraform format
        run: 
          terraform fmt
      
      - name: terraform init
        run: 
          terraform init 

      - name: terraform validate
        run: 
          terraform validate

      - name: terraform plan
        run: 
          terraform plan

#       - name: terraform apply
#         run: 
#           terraform apply -auto-approve
